### ISSUE TITLE
Ajustes gerais

### ISSUE THREAD

**Issue by Douglas-MRM** [guesant-study/pw-2bi-validacao-formularios#8]
#### Fala Galera!!!

Gostaria de sugerir duas melhorias relacionadas à nomenclatura dos arquivos HTML.

### 1 - Adoção de snake_case:
Atualmente, vocês estão utilizando **CamelCase** para nomear nossos arquivos HTML. No entanto, sugiro a transição para o padrão **snake_case**. Essa mudança trará benefícios em termos de compatibilidade e legibilidade do código.

Ao utilizar **snake_case**, evitaremos problemas de sensibilidade a maiúsculas e minúsculas em sistemas operacionais e servidores web, especialmente ao lidar com URLs.

Exemplo:
Atual: `cadastrarFornecedores.html`
Sugerido: `cadastrar_fornecedores.html`

### 2 - Nomenclatura singular:
Outra sugestão é ajustar a nomenclatura dos arquivos para o **singular**, em vez de **plural**. Essa alteração reflete a semântica correta, pois estamos efetuando o cadastro de um fornecedor individual, e não vários fornecedores simultaneamente.

Ao manter a nomenclatura no singular, tornamos o código mais claro e seguimos as melhores práticas de nomenclatura. Isso também ajudará na consistência e compreensão do projeto por parte de outros desenvolvedores.

Exemplo:
Atual: `cadastrar_fornecedores.html`
Sugerido: `cadastrar_fornecedor.html`

**Comment by xinnaider** [comment]
Quando eu crescer quero ser igual a esse cara aqui ó ☝️
